edit_uri: edit/master/docs/
site_author: Zachary Loeber
copyright: ModuleBuild is licensed under the <a href='https://github.com/zloeber/ModuleBuild/master/LICENSE.md'> license
theme: readthedocs
site_name: ModuleBuild Docs
Pages:
  Index: index.md
  Introduction: Introduction\Introduction.md
  Usage:
  - 1 - Initialization: Usage\1 - Initialization.md
  - 2 - Make Your Module: Usage\2 - Make Your Module.md
  - 3 - Build A Release: Usage\3 - Build A Release.md
  - 4 - Test A Release: Usage\4 - Test A Release.md
  - 5 - Publish A Release: Usage\5 - Publish A Release.md
  - 6 - Your Next Release: Usage\6 - Your Next Release.md
  - 7 - Project Documentation: Usage\7 - Project Documentation.md
  - 8 - Special Files: Usage\8 - Special Files.md
  - 9 - PSModuleBuild Configuration: Usage\9 - PSModuleBuild Configuration.md
  Functions:
  - Get-BuildEnvironment: Functions\Get-BuildEnvironment.md
  - Initialize-ModuleBuild: Functions\Initialize-ModuleBuild.md
  - Set-BuildEnvironment: Functions\Set-BuildEnvironment.md
  - Import-ModulePublicFunction: Functions\Import-ModulePublicFunction.md
  - Import-ModulePrivateFunction: Functions\Import-ModulePrivateFunction.md
  ToDo: ToDo.md
  Contributing: Contributing.md
  ChangeLog: ChangeLog.md
  Acknowledgements: Acknowledgements.md
repo_url: https://github.com/zloeber/ModuleBuild

